//
//  ChapterStore.swift
//  Weathero
//
//  Created by JiuZhiJiao on 18/4/21.
//

var chapters: [Chapter] = [
    .init(id: 11, topic: "Climate Change 1", chapterNO: 1, title: "Introduction", subtitle: "Global Warming and Natural Disasters", image: "ClimateChangeP1", video: "ClimateChangeC1", content: "👉Three attributes of climate:\n1️⃣ Atmospheric conditions\n2️⃣ In place\n3️⃣ For a long period of time\n\n👉The disappearance of lakes or even sea level rise are becoming more and more common.\n\n👉The number of natural disasters like droughts, floods or huge storms has increased."),
    .init(id: 12, topic: "Climate Change 2", chapterNO: 2, title: "Greenhouse Gas", subtitle: "Emissions Increased Recently", image: "ClimateChangeP2", video: "ClimateChangeC2", content: "👉The earth is surrounded by the atmosphere, a thin layer of gas which allows part of the solar radiation to penetrate.\n\n👉One of the main greenhouse gases is CO2.\n\n👉GHG’s capacity to retain solar radiation has been enhanced resulting in an increase of the average temperature of the planet."),
    .init(id: 13, topic: "Climate Change 3", chapterNO: 3, title: "Solutions", subtitle: "Tips to slow down Climate Change", image: "ClimateChangeP3", video: "ClimateChangeC3", content: "👉Over the past 150 years, the average global temperature increased almost 2 degrees fahrenheit, and the sea level has risen 7.5 inches.\n\n👉To reduce CO2 emissions:\n1️⃣ Use public transport,bicycle or walk.\n2️⃣ Reduce your plastic use. Use less plastic.\n3️⃣ Plant a tree.\n4️⃣ Always recycle.\n5️⃣ Turn off the lights whenever they are not needed."),
    .init(id: 21, topic: "Droughts 1", chapterNO: 1, title: "Introduction", subtitle: "Four Kinds of Droughts", image: "DroughtsP1", video: "DroughtsC1", content: "👉Drought truly becomes a disaster when it begins to affect crops and the lives of people and animals alike.\n\n👉Droughts can lead to the destruction of crops, erosion of soil, similar shortage of water supply, etc.\n\n👉Four different types of droughts:\n1️⃣ Meteorological drought\n2️⃣ Agricultural drought\n3️⃣ Hydrological drought\n4️⃣ Socioeconomic drought"),
    .init(id: 22, topic: "Droughts 2", chapterNO: 2, title: "Solutions", subtitle: "Tips to Survive Drought", image: "DroughtsP2", video: "DroughtsC2", content: "👉The one major rule you must keep in mind is saving water. \n\n👉Tips to save water:\n1️⃣ Wash fruits and vegetables in a bowl of water.\n2️⃣ Don’t leave the water running while washing your face.\n3️⃣ Take smaller shots or if you use a bathtub.\n4️⃣ And most importantly, recycle. Don’t waste water.\n\n👉Only 0.3% of water on earth is fresh water, available for human consumption. "),
    .init(id: 31, topic: "Floods 1", chapterNO: 1, title: "Introduction", subtitle: "Learning about Floods", image: "FloodsP1", video: "FloodsC1", content: "👉Some of the causes of Floods:\n\n1️⃣ Heavy Rains: This is one of the main causes of floods in Australia. This makes rivers exceed their capacity and causes them to overflow.\n\n2️⃣ Tsunami: The main causes of Tsunami are underwater earthquakes and volcanic eruptions.\n\n3️⃣ Hurricanes- The storms produce strong winds that push the water into shore, which can lead to flooding.\n\n4️⃣ Ice melts-These happen because of melting of significant amounts of fallen snow leading to flooding in neighbourhoods and water bodies.\n\n5️⃣ Breaking of Dams- Failure/Overflow of these barriers can result in floods. This is a rare cause of floods and can occur due to poor design, construction of dams or exceptionally high rainfalls."),
    .init(id: 32, topic: "Floods 2", chapterNO: 2, title: "Floods Type", subtitle: "3 Categories of Floods", image: "FloodsP2", video: "FloodsC2", content: "In Australia there are three common types of floods—slow-onset floods, and rapid-onset floods and flash floods.\n\n👉Slow-onset flooding\n1️⃣ occurs in the floodplains of inland rivers or streams\n2️⃣ floodwaters can spread over thousands of square miles (or square kilometers)\n3️⃣ This type of flood can last for weeks or even months\n4️⃣ Authorities are able to issue warnings in advance for this type of floods\n\n👉Rapid-onset flooding\n1️⃣ occurs more quickly and with less warning\n2️⃣ These floods happen where the slope is steeper, and the water flows faster\n3️⃣ These floods may last only a day or two\n4️⃣ It has a higher risk of death or property damage\n\n👉Flash floods\n1️⃣ occur due to very heavy rainfall over a short period of time\n2️⃣ Flash floods are sudden and difficult to predict, making them very dangerous."),
    .init(id: 33, topic: "Floods 3", chapterNO: 3, title: "Solutions", subtitle: "Save Yourself in Floods", image: "FloodsP3", video: "FloodsC3", content: "👉4 ways to keep yourself safe in Floods\n\n1️⃣ Never drive, ride or walk through floodwaters\n2️⃣ Never allow children to play near the flood water\n3️⃣ IF evacuated, do not return until it is safe to do so\n4️⃣ Follow the advice of authorities\n\n👉Do not panic in such a situation. Stay smart and stay safe.")
]
