//
//  ChapterStore.swift
//  Weathero
//
//  Created by JiuZhiJiao on 18/4/21.
//

var chapters: [Chapter] = [
    .init(id: 11, topic: "Climate Change", chapterNO: 1, title: "Introduction", subtitle: "Global Warming and Natural Disasters", image: "ClimateChangeP1", video: "ClimateChangeC1", content: "Have you ever heard of global warming?Did you know that over the past decades sea level has risen?\n\nAll these news are related to climate change. To understand what climate change is, we should define what climate is. The climate is the combination of atmospheric conditions that occur in place for a prolonged period of time. \n\nOver the past centuries, the climate everywhere around earth has changed altering the usual conditions of a place regarding precipitation and temperature. This way water shortage desertification, the disappearance of lakes or even sea level rise are becoming more and more common. \n\nIn addition, the number of natural disasters like droughts, floods or huge storms has increased.All these situations are a consequence of global warming, meaning the increase in temperature happening on the planet owing mainly to human activity."),
    .init(id: 12, topic: "Climate Change", chapterNO: 2, title: "Greenhouse Gas", subtitle: "Emissions Increased Recently", image: "ClimateChangeP2", video: "ClimateChangeC2", content: "Why has the planet’s temperature risen? The earth is surrounded by the atmosphere, a thin layer of gas which allows part of the solar radiation to penetrate. \n\nFor that this layer consists of gases called greenhouse effect gases whose mission is to absorb part of the energy received and maintain the planet's temperature. One of the main greenhouse gases is CO2. With the industrial revolution, CO2 emissions started to increase owing to the use of fossil fuels like coal or petrol. \n\nOver the past of years, the presence of gases like carbon dioxide in the atmosphere increased and for this reason, its capacity to retain solar radiation has been enhanced resulting in an increase of the average temperature of the planet."),
    .init(id: 13, topic: "Climate Change", chapterNO: 3, title: "Solutions", subtitle: "Tips to slow down Climate Change", image: "ClimateChangeP3", video: "ClimateChangeC3", content: "Climate change affects every country in the world causing a negative impact on their economy, people’s lives and all living beings. \n\nOver the past 150 years, the average global temperature increased almost 2 degrees fahrenheit. Would you say it’s not much? If the earth's temperature keeps rising, thousands of animal and plant species may disappear forever. Ocean got warmer and for this reason, the amounts of ice have decreased, causing sea level to rise. \n\nDid you know that between 1901 and 2010, the sea level has risen 7.5 inches? This may cause some places to disappear beneath the water’s surface. Worse consequences are predicted in the future if we don’t take measures urgently. Currently, there are some viable solutions at hand. Would you like to learn about them?It is necessary to turn to renewable energies to reduce CO2 emissions. Cars are responsible for 10 percent of co2 emissions. \n\nUse public transport,bicycle or walk. Reduce your plastic use. Use less plastic. Producing plastic involves high co2 emissions in the atmosphere. Plant a tree. Taking into account the ecological characteristics of your area. Did you know that five trees can absorb up to one metric ton of carbon dioxide during their life cycle? Always recycle. \n\nAn interesting fact is that we would need less energy to make paper from old newspapers than if we made it using wood directly from the wood from trees.Turn off the lights whenever they are not needed. If we save electricity, we also reduce the energy waste required to produce it."),
    .init(id: 21, topic: "Droughts", chapterNO: 1, title: "Droughts 01", subtitle: "Four Kinds of Droughts", image: "DroughtsP1", video: "DroughtsC1", content: "Droughts are usually defined  as extended periods of time with less than average rainfall causing a water shortage on the surface in the atmosphere or in the groundwater levels. It truly becomes a disaster when it begins to affect crops and the lives of people and animals alike.\n\nDroughts can be classified into 4 different types. These are:\n\nMeteorological drought: this kind of drought is specific to different regions based on the weather. For example, 20 inches of rainfall in a year is normal for place A but the same amount could be very less to place B.\n\nAgricultural drought: this accounts for the water needs of crops and agriculture. For instance, not enough water at planting may cause the wheels leading to low plant populations.\n\nHydrological drought: refers to continuous low water volumes in streams, rivers and reservoirs. Human activities can worsen hydrological droughts. Hydrological droughts are often linked  with meteorological droughts.\n\nSocioeconomic drought: this occurs when the demand for water exceeds the supply. Examples of this could be when a state requires a lot of more water than is produced from hydroelectric stations or underground wells."),
    .init(id: 31, topic: "FloodsP1", chapterNO: 1, title: "Floods 01", subtitle: "Here is the subtitle of floods chapter 01", image: "Floods", video: "ClimateChangeC1", content: "Here is the content")
]
